# @package path
data:
  validate: "data/processed/val_stratified_v1.csv"
  train: "data/processed/train_stratified_v1.csv"
  test: "data/processed/data_split_part3.csv"
  output: "outputs/submission_3.csv"