# @package path
data:
  validation: "data/processed/validation_rag_labeled_100.csv"
  train: "data/processed/train_stratified_v1.csv"
  test: "data/processed/data_split_part2.csv"
  output: "outputs/submission_2.csv"