defaults:
  - _self_
  - path: default
  - prompt/router@prompt.router
  - prompt/solver@prompt.solver
  - prompt/critic@prompt.critic
  - prompt/retrieval@prompt.retrieval
  - model/qwen2.5_32b@model.sub_solver
  - model/qwen3_32b@model.main_solver
  - model/qwen2.5_7b_it@model.router
system:
  device: "cuda"
  seed: 42
  project_name: "CSAT-Solver-Agent"

debug:
  test_indices: [14, 22, 99, 105]